columns:
- Freq_1: float64
- Freq_2: float64
- Freq_3: float64
- Freq_4: float64
- Freq_5: float64
- Freq_6: float64
- Freq_7: float64
- Freq_8: float64
- Freq_9: float64
- Freq_10: float64
- Freq_11: float64
- Freq_12: float64
- Freq_13: float64
- Freq_14: float64
- Freq_15: float64
- Freq_16: float64
- Freq_17: float64
- Freq_18: float64
- Freq_19: float64
- Freq_20: float64
- Freq_21: float64
- Freq_22: float64
- Freq_23: float64
- Freq_24: float64
- Freq_25: float64
- Freq_26: float64
- Freq_27: float64
- Freq_28: float64
- Freq_29: float64
- Freq_30: float64
- Freq_31: float64
- Freq_32: float64
- Freq_33: float64
- Freq_34: float64
- Freq_35: float64
- Freq_36: float64
- Freq_37: float64
- Freq_38: float64
- Freq_39: float64
- Freq_40: float64
- Freq_41: float64
- Freq_42: float64
- Freq_43: float64
- Freq_44: float64
- Freq_45: float64
- Freq_46: float64
- Freq_47: float64
- Freq_48: float64
- Freq_49: float64
- Freq_50: float64
- Freq_51: float64
- Freq_52: float64
- Freq_53: float64
- Freq_54: float64
- Freq_55: float64
- Freq_56: float64
- Freq_57: float64
- Freq_58: float64
- Freq_59: float64
- Freq_60: float64
- Label: object

numerical_columns:
  - Freq_1
  - Freq_2
  - Freq_3
  - Freq_4
  - Freq_5
  - Freq_6
  - Freq_7
  - Freq_8
  - Freq_9
  - Freq_10
  - Freq_11
  - Freq_12
  - Freq_13
  - Freq_14
  - Freq_15
  - Freq_16
  - Freq_17
  - Freq_18
  - Freq_19
  - Freq_20
  - Freq_21
  - Freq_22
  - Freq_23
  - Freq_24
  - Freq_25
  - Freq_26
  - Freq_27
  - Freq_28
  - Freq_29
  - Freq_30
  - Freq_31
  - Freq_32
  - Freq_33
  - Freq_34
  - Freq_35
  - Freq_36
  - Freq_37
  - Freq_38
  - Freq_39
  - Freq_40
  - Freq_41
  - Freq_42
  - Freq_43
  - Freq_44
  - Freq_45
  - Freq_46
  - Freq_47
  - Freq_48
  - Freq_49
  - Freq_50
  - Freq_51
  - Freq_52
  - Freq_53
  - Freq_54
  - Freq_55
  - Freq_56
  - Freq_57
  - Freq_58
  - Freq_59
  - Freq_60